REQUIRED_PLUGINS = %w(vagrant-haipa,vagrant-omnibus)

Vagrant.configure('2') do |config|
 # config.omnibus.chef_version = :latest

  config.ssh.username = 'ubuntu'
  config.ssh.password = 'vagrant'
  #config.ssh.private_key_path = 'test_id_rsa'
  #config.vm.allowed_synced_folder_types = [:rsync]
  config.vm.synced_folder ".", "/vagrant", disabled: true
 
  config.vm.provider :haipa do |provider, override|
    override.vm.box = 'haipa'
    override.vm.box_url = "https://github.com/haipa/vagrant-haipa/raw/master/box/haipa.box"
    provider.token = ENV['DO_TOKEN']
    #provider.ssh_key_name = 'Test Key'
  end

  #config.vm.provision :shell, :path => 'scripts/provision.sh'

  #config.vm.provision :chef_solo do |chef|
  #  chef.cookbooks_path = 'cookbooks'
  #  chef.add_recipe 'test'
  #end

  config.vm.define :ubuntu do |ubuntu|
    ubuntu.vm.provider :haipa do |provider|
      provider.image = 'ubuntu-14-04-x64'
      provider.vm_config = {
        'Path' => 't:\\openstack\\vms',
        'Memory' => {
          'Startup' => 2048
        },
        'Disks' => [
          {
            "Template" => 't:\\openstack\\ubuntu-xenial.vhdx',
            "Size" => 20
          }
        ],  
        'NetworkAdapters' => [
          {
            "Name" => "eth0",
            "SwitchName" => "Default Switch",
          }                                                          
        ] ,
      }

      provider.provision = {
        'Hostname' => 'basic',
        "UserData" => {
          "password" => config.ssh.password,
          "chpasswd" => {
            "expire"=> "False"
        }
      }
    }
    end
  end

  #config.vm.define :centos do |centos|
  #  centos.vm.provider :haipa do |provider|
  #    provider.image = 'centos-6-5-x64'
  #  end
  #end
end
