REQUIRED_PLUGINS = %w(vagrant-haipa)

Vagrant.configure('2') do |config|

  config.ssh.username = 'ubuntu'
  config.ssh.password = 'vagrant'

  config.vm.synced_folder ".", "/vagrant", disabled: true
 
  #config.vm.provision :shell, :path => 'scripts/provision.sh'

  config.vm.define :ubuntu do |ubuntu|
    ubuntu.vm.provider :haipa do |provider|
      provider.vm_config = {
         'Memory' => {
          'Startup' => 2048
        },
        'Disks' => [
          {
            "Template" => 'T:\openstack\ubuntu-xenial.vhdx',
            "Size" => 20
          }
        ],  
        'NetworkAdapters' => [
          {
            "Name" => "eth0",
            "SwitchName" => "Default Switch",
          }                                                          
        ] ,
      }

      provider.provision = {
        'Hostname' => 'basic',
        "UserData" => {
          "password" => config.ssh.password,
          "chpasswd" => {
            "expire"=> "False"
        }
      }
    }
    end
  end
end
